ControleDeGastos/Models/Orcamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeGastos.Models
{
    public class Orcamento
    {
        [Key]
        public int ID { get; set; }
        [ForeignKey("MesID")]
        public Mes Mes { get; set; }
        public int Ano { get; set; }
        public string Descricao { get; set; }
    }
}

ControleDeGastos/Controllers/ItemOrcamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControleDeGastos.Data;
using ControleDeGastos.Models;

namespace ControleDeGastos.Views
{
    public class ItemOrcamentoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemOrcamentoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ItemOrcamento
        public async Task<IActionResult> Index()
        {
            return View(await _context.ItemOrcamento.ToListAsync());
        }
        public async Task<List<Categoria>> ListaCategorias()
        {
            var categorias = _context.Categoria;
            return await categorias.ToListAsync();
        }
        // GET: ItemOrcamento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemOrcamento = await _context.ItemOrcamento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemOrcamento == null)
            {
                return NotFound();
            }

            return View(itemOrcamento);
        }

        // GET: ItemOrcamento/Create
        public IActionResult Create(int? id)
        {
            var categorias = ListaCategorias().Result;
            ViewBag.Categorias = new SelectList(categorias, "ID", "Descricao");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Descricao,Categoria,Valor,Orcamento")] ItemOrcamento itemOrcamento, int? id)
        {
            if (ModelState.IsValid)
            {
                itemOrcamento.Orcamentos = await _context.Orcamento
                .FirstOrDefaultAsync(m => m.ID == id);
                _context.Add(itemOrcamento);
                //_context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(itemOrcamento);
        }

        // GET: ItemOrcamento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemOrcamento = await _context.ItemOrcamento.FindAsync(id);
            if (itemOrcamento == null)
            {
                return NotFound();
            }
            return View(itemOrcamento);
        }

        // POST: ItemOrcamento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Descricao,Valor")] ItemOrcamento itemOrcamento)
        {
            if (id != itemOrcamento.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemOrcamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemOrcamentoExists(itemOrcamento.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemOrcamento);
        }

        // GET: ItemOrcamento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemOrcamento = await _context.ItemOrcamento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemOrcamento == null)
            {
                return NotFound();
            }

            return View(itemOrcamento);
        }

        // POST: ItemOrcamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var itemOrcamento = await _context.ItemOrcamento.FindAsync(id);
            _context.ItemOrcamento.Remove(itemOrcamento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemOrcamentoExists(int id)
        {
            return _context.ItemOrcamento.Any(e => e.ID == id);
        }
    }
}

ControleDeGastos/Controllers/OrcamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControleDeGastos.Data;
using ControleDeGastos.Models;

namespace ControleDeGastos.Views
{
    public class OrcamentosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrcamentosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orcamentoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orcamento.ToListAsync());
        }

        public async Task<List<Mes>> ListaMeses()
        {
            var meses = _context.Mes.ToListAsync();
            return await meses;
        }
        public async Task<List<Categoria>> ListaCategorias()
        {
            var categorias = _context.Categoria;
            return await categorias.ToListAsync();
        }
        // GET: Orcamentoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orcamento = await _context.Orcamento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (orcamento == null)
            {
                return NotFound();
            }

            return View(orcamento);
        }

        // GET: Orcamentoes/Create
        public IActionResult Create()
        {
            var meses = ListaMeses();
            ViewData["Meses"] = new SelectList(meses.Result, "Id", "Mes");
            var categorias = ListaCategorias().Result;

            ViewBag.Categorias = new SelectList(categorias, "Id", "Categoria"); 
            return View();
        }

        // POST: Orcamentoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Ano,Descricao,Valor,Mes,Categoria")] Orcamento orcamento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orcamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orcamento);
        }

        // GET: Orcamentoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orcamento = await _context.Orcamento.FindAsync(id);
            if (orcamento == null)
            {
                return NotFound();
            }
            return View(orcamento);
        }

        // POST: Orcamentoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Ano,Descricao,Valor,Mes,Categoria")] Orcamento orcamento)
        {
            if (id != orcamento.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orcamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrcamentoExists(orcamento.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orcamento);
        }

        // GET: Orcamentoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orcamento = await _context.Orcamento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (orcamento == null)
            {
                return NotFound();
            }

            return View(orcamento);
        }

        // POST: Orcamentoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orcamento = await _context.Orcamento.FindAsync(id);
            _context.Orcamento.Remove(orcamento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrcamentoExists(int id)
        {
            return _context.Orcamento.Any(e => e.ID == id);
        }
    }
}

ControleDeGastos/Views/Orcamentos/Create.cshtml
@model ControleDeGastos.Models.Orcamento
@using ControleDeGastos.Models
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Meses = new SelectList(new object[]
{
new {Mes = "Janeiro", Value = "1"},
new {Mes = "Fevereiro", Value = "2"},
new {Mes = "Março", Value = "3"},
new {Mes = "Abril", Value = "4"},
new {Mes = "Maio", Value = "5"},
new {Mes = "Junho", Value = "6"},
new {Mes = "Julho", Value = "7"},
new {Mes = "Agosto", Value = "8"},
new {Mes = "Setembro", Value = "9"},
new {Mes = "Outubro", Value = "10"},
new {Mes = "Novembro", Value = "11"},
new {Mes = "Dezembro", Value = "12"}
}, "Value", "Mes");
}
@{
    var categoria = ViewBag.Categorias;
}

<h4>Criar Orçamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mes" class="control-label">Mes</label>
                <select asp-for="Mes" class="form-control" asp-items="@ViewBag.Meses"></select>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeGastos/Views/Orcamentos/Delete.cshtml
@model ControleDeGastos.Models.Orcamento

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orcamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ControleDeGastos/Views/Orcamentos/Details.cshtml
@model ControleDeGastos.Models.Orcamento

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Orcamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ControleDeGastos/Views/Orcamentos/Edit.cshtml
@model ControleDeGastos.Models.Orcamento

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Orcamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeGastos/Views/Orcamentos/Index.cshtml
@model IEnumerable<ControleDeGastos.Models.Orcamento>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID"> <i class="fas fa-edit"></i></a> |
                <a asp-controller="ItemOrcamento" asp-action="Create" asp-route-id="@item.ID"><i class="fas fa-plus"></i></a> |
                <a asp-action="Delete" asp-route-id="@item.ID"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>